// Code generated by Kubegraph; DO NOT EDIT.

package v1beta1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	coreV1 "k8s.io/api/core/v1"
)

// ServiceObject alias for coreV1.Service
type ServiceObject = coreV1.Service

// ServiceAdapterObjectType reflected type of *coreV1.Service
var ServiceAdapterObjectType = reflect.TypeOf((*coreV1.Service)(nil))

// GetServiceAdapter retrieves the adapter that handles
// coreV1.Service resources from the registry, if any
func GetServiceAdapter() (registry.ResourceAdapter[*coreV1.Service], error) {
	adapter, err := registry.GetAdapter[*coreV1.Service]()
	if err != nil {
		return nil, fmt.Errorf("failed to get adapter: %w", registry.ErrIncompatibleType)
	}

	return adapter, nil
}
