// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	coreV1 "k8s.io/api/core/v1"
)

// ConfigMapObject alias for coreV1.ConfigMap
type ConfigMapObject = coreV1.ConfigMap

// ConfigMapAdapterObjectType reflected type of *coreV1.ConfigMap
var ConfigMapAdapterObjectType = reflect.TypeOf((*coreV1.ConfigMap)(nil))

// GetConfigMapAdapter retrieves *ConfigMapAdapter from the registry
func GetConfigMapAdapter() (*ConfigMapAdapter, error) {
	adapter, err := registry.GetAdapter[*coreV1.ConfigMap]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*ConfigMapAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// ConfigMapAdapter implements an adapter for coreV1.ConfigMap
type ConfigMapAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *coreV1.ConfigMap
func (this *ConfigMapAdapter) CastObject(obj registry.RuntimeObject) (*coreV1.ConfigMap, error) {
	casted, ok := obj.(*coreV1.ConfigMap)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *coreV1.ConfigMap
// nodes stored on a graph
func (this *ConfigMapAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*coreV1.ConfigMap, error) {
	objects, err := statefulGraph.GetObjects(ConfigMapAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*coreV1.ConfigMap, len(objects))
	for key, object := range objects {
		casted, ok := object.(*coreV1.ConfigMap)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *coreV1.ConfigMap
func (this *ConfigMapAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(ConfigMapAdapterObjectType, name)
}

func (this *ConfigMapAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/cm.svg")
}

// init registers ConfigMapAdapter
func init() {
	registry.MustRegister(&ConfigMapAdapter{
		registry.NewAdapter(
			ConfigMapAdapterObjectType,
			"icons/cm.svg",
		),
	})
}
