// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	coreV1 "k8s.io/api/core/v1"
)

// PersistentVolumeObject alias for coreV1.PersistentVolume
type PersistentVolumeObject = coreV1.PersistentVolume

// PersistentVolumeAdapterObjectType reflected type of *coreV1.PersistentVolume
var PersistentVolumeAdapterObjectType = reflect.TypeOf((*coreV1.PersistentVolume)(nil))

// GetPersistentVolumeAdapter retrieves *PersistentVolumeAdapter from the registry
func GetPersistentVolumeAdapter() (*PersistentVolumeAdapter, error) {
	adapter, err := registry.GetAdapter[*coreV1.PersistentVolume]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*PersistentVolumeAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// PersistentVolumeAdapter implements an adapter for coreV1.PersistentVolume
type PersistentVolumeAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *coreV1.PersistentVolume
func (this *PersistentVolumeAdapter) CastObject(obj registry.RuntimeObject) (*coreV1.PersistentVolume, error) {
	casted, ok := obj.(*coreV1.PersistentVolume)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *coreV1.PersistentVolume
// nodes stored on a graph
func (this *PersistentVolumeAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*coreV1.PersistentVolume, error) {
	objects, err := statefulGraph.GetObjects(PersistentVolumeAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*coreV1.PersistentVolume, len(objects))
	for key, object := range objects {
		casted, ok := object.(*coreV1.PersistentVolume)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *coreV1.PersistentVolume
func (this *PersistentVolumeAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(PersistentVolumeAdapterObjectType, name)
}

func (this *PersistentVolumeAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/pv.svg")
}

// init registers PersistentVolumeAdapter
func init() {
	registry.MustRegister(&PersistentVolumeAdapter{
		registry.NewAdapter(
			PersistentVolumeAdapterObjectType,
			"icons/pv.svg",
		),
	})
}
