// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	coreV1 "k8s.io/api/core/v1"
)

// PodObject alias for coreV1.Pod
type PodObject = coreV1.Pod

// PodAdapterObjectType reflected type of *coreV1.Pod
var PodAdapterObjectType = reflect.TypeOf((*coreV1.Pod)(nil))

// GetPodAdapter retrieves *PodAdapter from the registry
func GetPodAdapter() (*PodAdapter, error) {
	adapter, err := registry.GetAdapter[*coreV1.Pod]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*PodAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// PodAdapter implements an adapter for coreV1.Pod
type PodAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *coreV1.Pod
func (this *PodAdapter) CastObject(obj registry.RuntimeObject) (*coreV1.Pod, error) {
	casted, ok := obj.(*coreV1.Pod)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *coreV1.Pod
// nodes stored on a graph
func (this *PodAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*coreV1.Pod, error) {
	objects, err := statefulGraph.GetObjects(PodAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*coreV1.Pod, len(objects))
	for key, object := range objects {
		casted, ok := object.(*coreV1.Pod)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *coreV1.Pod
func (this *PodAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(PodAdapterObjectType, name)
}

func (this *PodAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/pod.svg")
}

// init registers PodAdapter
func init() {
	registry.MustRegister(&PodAdapter{
		registry.NewAdapter(
			PodAdapterObjectType,
			"icons/pod.svg",
		),
	})
}
