// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	coreV1 "k8s.io/api/core/v1"
)

// SecretObject alias for coreV1.Secret
type SecretObject = coreV1.Secret

// SecretAdapterObjectType reflected type of *coreV1.Secret
var SecretAdapterObjectType = reflect.TypeOf((*coreV1.Secret)(nil))

// GetSecretAdapter retrieves *SecretAdapter from the registry
func GetSecretAdapter() (*SecretAdapter, error) {
	adapter, err := registry.GetAdapter[*coreV1.Secret]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*SecretAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// SecretAdapter implements an adapter for coreV1.Secret
type SecretAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *coreV1.Secret
func (this *SecretAdapter) CastObject(obj registry.RuntimeObject) (*coreV1.Secret, error) {
	casted, ok := obj.(*coreV1.Secret)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *coreV1.Secret
// nodes stored on a graph
func (this *SecretAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*coreV1.Secret, error) {
	objects, err := statefulGraph.GetObjects(SecretAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*coreV1.Secret, len(objects))
	for key, object := range objects {
		casted, ok := object.(*coreV1.Secret)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *coreV1.Secret
func (this *SecretAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(SecretAdapterObjectType, name)
}

func (this *SecretAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/secret.svg")
}

// init registers SecretAdapter
func init() {
	registry.MustRegister(&SecretAdapter{
		registry.NewAdapter(
			SecretAdapterObjectType,
			"icons/secret.svg",
		),
	})
}
