// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	coreV1 "k8s.io/api/core/v1"
)

// ServiceAccountObject alias for coreV1.ServiceAccount
type ServiceAccountObject = coreV1.ServiceAccount

// ServiceAccountAdapterObjectType reflected type of *coreV1.ServiceAccount
var ServiceAccountAdapterObjectType = reflect.TypeOf((*coreV1.ServiceAccount)(nil))

// GetServiceAccountAdapter retrieves *ServiceAccountAdapter from the registry
func GetServiceAccountAdapter() (*ServiceAccountAdapter, error) {
	adapter, err := registry.GetAdapter[*coreV1.ServiceAccount]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*ServiceAccountAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// ServiceAccountAdapter implements an adapter for coreV1.ServiceAccount
type ServiceAccountAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *coreV1.ServiceAccount
func (this *ServiceAccountAdapter) CastObject(obj registry.RuntimeObject) (*coreV1.ServiceAccount, error) {
	casted, ok := obj.(*coreV1.ServiceAccount)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *coreV1.ServiceAccount
// nodes stored on a graph
func (this *ServiceAccountAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*coreV1.ServiceAccount, error) {
	objects, err := statefulGraph.GetObjects(ServiceAccountAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*coreV1.ServiceAccount, len(objects))
	for key, object := range objects {
		casted, ok := object.(*coreV1.ServiceAccount)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *coreV1.ServiceAccount
func (this *ServiceAccountAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(ServiceAccountAdapterObjectType, name)
}

func (this *ServiceAccountAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/sa.svg")
}

// init registers ServiceAccountAdapter
func init() {
	registry.MustRegister(&ServiceAccountAdapter{
		registry.NewAdapter(
			ServiceAccountAdapterObjectType,
			"icons/sa.svg",
		),
	})
}
