// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	coreV1 "k8s.io/api/core/v1"
)

// ServiceObject alias for coreV1.Service
type ServiceObject = coreV1.Service

// ServiceAdapterObjectType reflected type of *coreV1.Service
var ServiceAdapterObjectType = reflect.TypeOf((*coreV1.Service)(nil))

// GetServiceAdapter retrieves *ServiceAdapter from the registry
func GetServiceAdapter() (*ServiceAdapter, error) {
	adapter, err := registry.GetAdapter[*coreV1.Service]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*ServiceAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// ServiceAdapter implements an adapter for coreV1.Service
type ServiceAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *coreV1.Service
func (this *ServiceAdapter) CastObject(obj registry.RuntimeObject) (*coreV1.Service, error) {
	casted, ok := obj.(*coreV1.Service)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *coreV1.Service
// nodes stored on a graph
func (this *ServiceAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*coreV1.Service, error) {
	objects, err := statefulGraph.GetObjects(ServiceAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*coreV1.Service, len(objects))
	for key, object := range objects {
		casted, ok := object.(*coreV1.Service)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *coreV1.Service
func (this *ServiceAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(ServiceAdapterObjectType, name)
}

func (this *ServiceAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/svc.svg")
}

// init registers ServiceAdapter
func init() {
	registry.MustRegister(&ServiceAdapter{
		registry.NewAdapter(
			ServiceAdapterObjectType,
			"icons/svc.svg",
		),
	})
}
