// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	appsV1 "k8s.io/api/apps/v1"
)

// StatefulSetObject alias for appsV1.StatefulSet
type StatefulSetObject = appsV1.StatefulSet

// StatefulSetAdapterObjectType reflected type of *appsV1.StatefulSet
var StatefulSetAdapterObjectType = reflect.TypeOf((*appsV1.StatefulSet)(nil))

// GetStatefulSetAdapter retrieves *StatefulSetAdapter from the registry
func GetStatefulSetAdapter() (*StatefulSetAdapter, error) {
	adapter, err := registry.GetAdapter[*appsV1.StatefulSet]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*StatefulSetAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// StatefulSetAdapter implements an adapter for appsV1.StatefulSet
type StatefulSetAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *appsV1.StatefulSet
func (this *StatefulSetAdapter) CastObject(obj registry.RuntimeObject) (*appsV1.StatefulSet, error) {
	casted, ok := obj.(*appsV1.StatefulSet)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *appsV1.StatefulSet
// nodes stored on a graph
func (this *StatefulSetAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*appsV1.StatefulSet, error) {
	objects, err := statefulGraph.GetObjects(StatefulSetAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*appsV1.StatefulSet, len(objects))
	for key, object := range objects {
		casted, ok := object.(*appsV1.StatefulSet)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *appsV1.StatefulSet
func (this *StatefulSetAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(StatefulSetAdapterObjectType, name)
}

func (this *StatefulSetAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/sts.svg")
}

// init registers StatefulSetAdapter
func init() {
	registry.MustRegister(&StatefulSetAdapter{
		registry.NewAdapter(
			StatefulSetAdapterObjectType,
			"icons/sts.svg",
		),
	})
}
