// Code generated by Kubegraph; DO NOT EDIT.

package v1beta1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	coreV1 "k8s.io/api/core/v1"
)

// ServiceAccountObject alias for coreV1.ServiceAccount
type ServiceAccountObject = coreV1.ServiceAccount

// ServiceAccountAdapterObjectType reflected type of *coreV1.ServiceAccount
var ServiceAccountAdapterObjectType = reflect.TypeOf((*coreV1.ServiceAccount)(nil))

// GetServiceAccountAdapter retrieves the adapter that handles
// coreV1.ServiceAccount resources from the registry, if any
func GetServiceAccountAdapter() (registry.ResourceAdapter[*coreV1.ServiceAccount], error) {
	adapter, err := registry.GetAdapter[*coreV1.ServiceAccount]()
	if err != nil {
		return nil, fmt.Errorf("failed to get adapter: %w", registry.ErrIncompatibleType)
	}

	return adapter, nil
}
