// Code generated by Kubegraph; DO NOT EDIT.

package v1beta1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	policyV1beta1 "k8s.io/api/policy/v1beta1"
)

// PolicyV1beta1PodSecurityPolicyObject alias for policyV1beta1.PodSecurityPolicy
type PolicyV1beta1PodSecurityPolicyObject = policyV1beta1.PodSecurityPolicy

// PolicyV1beta1PodSecurityPolicyAdapterObjectType reflected type of *policyV1beta1.PodSecurityPolicy
var PolicyV1beta1PodSecurityPolicyAdapterObjectType = reflect.TypeOf((*policyV1beta1.PodSecurityPolicy)(nil))

// GetPolicyV1beta1PodSecurityPolicyAdapter retrieves the adapter that handles
// policyV1beta1.PodSecurityPolicy resources from the registry, if any
func GetPolicyV1beta1PodSecurityPolicyAdapter() (registry.ResourceAdapter[*policyV1beta1.PodSecurityPolicy], error) {
	adapter, err := registry.GetAdapter[*policyV1beta1.PodSecurityPolicy]()
	if err != nil {
		return nil, fmt.Errorf("failed to get adapter: %w", registry.ErrIncompatibleType)
	}

	return adapter, nil
}
