// Code generated by Kubegraph; DO NOT EDIT.

package v1beta1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	rbacV1 "k8s.io/api/rbac/v1"
)

// RbacV1RoleObject alias for rbacV1.Role
type RbacV1RoleObject = rbacV1.Role

// RbacV1RoleAdapterObjectType reflected type of *rbacV1.Role
var RbacV1RoleAdapterObjectType = reflect.TypeOf((*rbacV1.Role)(nil))

// GetRbacV1RoleAdapter retrieves the adapter that handles
// rbacV1.Role resources from the registry, if any
func GetRbacV1RoleAdapter() (registry.ResourceAdapter[*rbacV1.Role], error) {
	adapter, err := registry.GetAdapter[*rbacV1.Role]()
	if err != nil {
		return nil, fmt.Errorf("failed to get adapter: %w", registry.ErrIncompatibleType)
	}

	return adapter, nil
}
