// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package kubegraph

import (
	"github.com/wwmoraes/dot"
	"github.com/wwmoraes/kubegraph/internal/adapters"
	"github.com/wwmoraes/kubegraph/internal/registry"
)

import (
	_ "github.com/wwmoraes/kubegraph/internal/adapters"
)

// Injectors from wire.go:

func InitializeKubegraph(optionsFn ...dot.GraphOptionFn) (*Kubegraph, error) {
	graph, err := dot.New(optionsFn...)
	if err != nil {
		return nil, err
	}
	registryRegistry := registry.Instance()
	decodeFn := adapters.GetDecoder()
	kubegraph := NewKubegraph(graph, registryRegistry, decodeFn)
	return kubegraph, nil
}
