// Code generated by Kubegraph; DO NOT EDIT.

package v2beta1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	appsV1 "k8s.io/api/apps/v1"
)

// DeploymentObject alias for appsV1.Deployment
type DeploymentObject = appsV1.Deployment

// DeploymentAdapterObjectType reflected type of *appsV1.Deployment
var DeploymentAdapterObjectType = reflect.TypeOf((*appsV1.Deployment)(nil))

// GetDeploymentAdapter retrieves the adapter that handles
// appsV1.Deployment resources from the registry, if any
func GetDeploymentAdapter() (registry.ResourceAdapter[*appsV1.Deployment], error) {
	adapter, err := registry.GetAdapter[*appsV1.Deployment]()
	if err != nil {
		return nil, fmt.Errorf("failed to get adapter: %w", registry.ErrIncompatibleType)
	}

	return adapter, nil
}
