// Code generated by Kubegraph; DO NOT EDIT.

package v1alpha3

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	networkV1alpha3 "istio.io/client-go/pkg/apis/networking/v1alpha3"
)

// GatewayObject alias for networkV1alpha3.Gateway
type GatewayObject = networkV1alpha3.Gateway

// GatewayAdapterObjectType reflected type of *networkV1alpha3.Gateway
var GatewayAdapterObjectType = reflect.TypeOf((*networkV1alpha3.Gateway)(nil))

// GetGatewayAdapter retrieves *GatewayAdapter from the registry
func GetGatewayAdapter() (*GatewayAdapter, error) {
	adapter, err := registry.GetAdapter[*networkV1alpha3.Gateway]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*GatewayAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// GatewayAdapter implements an adapter for networkV1alpha3.Gateway
type GatewayAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *networkV1alpha3.Gateway
func (this *GatewayAdapter) CastObject(obj registry.RuntimeObject) (*networkV1alpha3.Gateway, error) {
	casted, ok := obj.(*networkV1alpha3.Gateway)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *networkV1alpha3.Gateway
// nodes stored on a graph
func (this *GatewayAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*networkV1alpha3.Gateway, error) {
	objects, err := statefulGraph.GetObjects(GatewayAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*networkV1alpha3.Gateway, len(objects))
	for key, object := range objects {
		casted, ok := object.(*networkV1alpha3.Gateway)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *networkV1alpha3.Gateway
func (this *GatewayAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(GatewayAdapterObjectType, name)
}

func (this *GatewayAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/unknown.svg")
}

// init registers GatewayAdapter
func init() {
	registry.MustRegister(&GatewayAdapter{
		registry.NewAdapter(
			GatewayAdapterObjectType,
			"icons/unknown.svg",
		),
	})
}
