// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	rbacV1 "k8s.io/api/rbac/v1"
)

// ClusterRoleObject alias for rbacV1.ClusterRole
type ClusterRoleObject = rbacV1.ClusterRole

// ClusterRoleAdapterObjectType reflected type of *rbacV1.ClusterRole
var ClusterRoleAdapterObjectType = reflect.TypeOf((*rbacV1.ClusterRole)(nil))

// GetClusterRoleAdapter retrieves *ClusterRoleAdapter from the registry
func GetClusterRoleAdapter() (*ClusterRoleAdapter, error) {
	adapter, err := registry.GetAdapter[*rbacV1.ClusterRole]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*ClusterRoleAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// ClusterRoleAdapter implements an adapter for rbacV1.ClusterRole
type ClusterRoleAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *rbacV1.ClusterRole
func (this *ClusterRoleAdapter) CastObject(obj registry.RuntimeObject) (*rbacV1.ClusterRole, error) {
	casted, ok := obj.(*rbacV1.ClusterRole)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *rbacV1.ClusterRole
// nodes stored on a graph
func (this *ClusterRoleAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*rbacV1.ClusterRole, error) {
	objects, err := statefulGraph.GetObjects(ClusterRoleAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*rbacV1.ClusterRole, len(objects))
	for key, object := range objects {
		casted, ok := object.(*rbacV1.ClusterRole)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *rbacV1.ClusterRole
func (this *ClusterRoleAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(ClusterRoleAdapterObjectType, name)
}

func (this *ClusterRoleAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/c-role.svg")
}

// init registers ClusterRoleAdapter
func init() {
	registry.MustRegister(&ClusterRoleAdapter{
		registry.NewAdapter(
			ClusterRoleAdapterObjectType,
			"icons/c-role.svg",
		),
	})
}
