// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	rbacV1beta1 "k8s.io/api/rbac/v1beta1"
)

// RbacV1beta1RoleObject alias for rbacV1beta1.Role
type RbacV1beta1RoleObject = rbacV1beta1.Role

// RbacV1beta1RoleAdapterObjectType reflected type of *rbacV1beta1.Role
var RbacV1beta1RoleAdapterObjectType = reflect.TypeOf((*rbacV1beta1.Role)(nil))

// GetRbacV1beta1RoleAdapter retrieves the adapter that handles
// rbacV1beta1.Role resources from the registry, if any
func GetRbacV1beta1RoleAdapter() (registry.ResourceAdapter[*rbacV1beta1.Role], error) {
	adapter, err := registry.GetAdapter[*rbacV1beta1.Role]()
	if err != nil {
		return nil, fmt.Errorf("failed to get adapter: %w", registry.ErrIncompatibleType)
	}

	return adapter, nil
}
