// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	rbacV1beta1 "k8s.io/api/rbac/v1beta1"
)

// RbacV1beta1ClusterRoleObject alias for rbacV1beta1.ClusterRole
type RbacV1beta1ClusterRoleObject = rbacV1beta1.ClusterRole

// RbacV1beta1ClusterRoleAdapterObjectType reflected type of *rbacV1beta1.ClusterRole
var RbacV1beta1ClusterRoleAdapterObjectType = reflect.TypeOf((*rbacV1beta1.ClusterRole)(nil))

// GetRbacV1beta1ClusterRoleAdapter retrieves the adapter that handles
// rbacV1beta1.ClusterRole resources from the registry, if any
func GetRbacV1beta1ClusterRoleAdapter() (registry.ResourceAdapter[*rbacV1beta1.ClusterRole], error) {
	adapter, err := registry.GetAdapter[*rbacV1beta1.ClusterRole]()
	if err != nil {
		return nil, fmt.Errorf("failed to get adapter: %w", registry.ErrIncompatibleType)
	}

	return adapter, nil
}
