// Code generated by Kubegraph; DO NOT EDIT.

package adapters

import (
	"fmt"
	"os"

	"k8s.io/client-go/kubernetes/scheme"
	aggregatorScheme "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme"
)

func init() {
	if err := aggregatorScheme.AddToScheme(scheme.Scheme); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
