// Code generated by Kubegraph; DO NOT EDIT.

package adapters

import (
	"fmt"
	"os"

	apiExtensionsScheme "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme"
	"k8s.io/client-go/kubernetes/scheme"
)

func init() {
	if err := apiExtensionsScheme.AddToScheme(scheme.Scheme); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
