// Code generated by Kubegraph; DO NOT EDIT.

package adapters

import (
	"fmt"
	"os"

	"k8s.io/client-go/kubernetes/scheme"
	applicationScheme "sigs.k8s.io/application/api/v1beta1"
)

func init() {
	if err := applicationScheme.AddToScheme(scheme.Scheme); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
