// Code generated by Kubegraph; DO NOT EDIT.

package adapters

import (
	"fmt"
	"os"

	istioScheme "istio.io/client-go/pkg/clientset/versioned/scheme"
	"k8s.io/client-go/kubernetes/scheme"
)

func init() {
	if err := istioScheme.AddToScheme(scheme.Scheme); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
