// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	appsV1 "k8s.io/api/apps/v1"
)

// DaemonSetObject alias for appsV1.DaemonSet
type DaemonSetObject = appsV1.DaemonSet

// DaemonSetAdapterObjectType reflected type of *appsV1.DaemonSet
var DaemonSetAdapterObjectType = reflect.TypeOf((*appsV1.DaemonSet)(nil))

// GetDaemonSetAdapter retrieves *DaemonSetAdapter from the registry
func GetDaemonSetAdapter() (*DaemonSetAdapter, error) {
	adapter, err := registry.GetAdapter[*appsV1.DaemonSet]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*DaemonSetAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// DaemonSetAdapter implements an adapter for appsV1.DaemonSet
type DaemonSetAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *appsV1.DaemonSet
func (this *DaemonSetAdapter) CastObject(obj registry.RuntimeObject) (*appsV1.DaemonSet, error) {
	casted, ok := obj.(*appsV1.DaemonSet)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *appsV1.DaemonSet
// nodes stored on a graph
func (this *DaemonSetAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*appsV1.DaemonSet, error) {
	objects, err := statefulGraph.GetObjects(DaemonSetAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*appsV1.DaemonSet, len(objects))
	for key, object := range objects {
		casted, ok := object.(*appsV1.DaemonSet)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *appsV1.DaemonSet
func (this *DaemonSetAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(DaemonSetAdapterObjectType, name)
}

func (this *DaemonSetAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/ds.svg")
}

// init registers DaemonSetAdapter
func init() {
	registry.MustRegister(&DaemonSetAdapter{
		registry.NewAdapter(
			DaemonSetAdapterObjectType,
			"icons/ds.svg",
		),
	})
}
