// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	appsV1 "k8s.io/api/apps/v1"
)

// DeploymentObject alias for appsV1.Deployment
type DeploymentObject = appsV1.Deployment

// DeploymentAdapterObjectType reflected type of *appsV1.Deployment
var DeploymentAdapterObjectType = reflect.TypeOf((*appsV1.Deployment)(nil))

// GetDeploymentAdapter retrieves *DeploymentAdapter from the registry
func GetDeploymentAdapter() (*DeploymentAdapter, error) {
	adapter, err := registry.GetAdapter[*appsV1.Deployment]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*DeploymentAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// DeploymentAdapter implements an adapter for appsV1.Deployment
type DeploymentAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *appsV1.Deployment
func (this *DeploymentAdapter) CastObject(obj registry.RuntimeObject) (*appsV1.Deployment, error) {
	casted, ok := obj.(*appsV1.Deployment)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *appsV1.Deployment
// nodes stored on a graph
func (this *DeploymentAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*appsV1.Deployment, error) {
	objects, err := statefulGraph.GetObjects(DeploymentAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*appsV1.Deployment, len(objects))
	for key, object := range objects {
		casted, ok := object.(*appsV1.Deployment)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *appsV1.Deployment
func (this *DeploymentAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(DeploymentAdapterObjectType, name)
}

func (this *DeploymentAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/deploy.svg")
}

// init registers DeploymentAdapter
func init() {
	registry.MustRegister(&DeploymentAdapter{
		registry.NewAdapter(
			DeploymentAdapterObjectType,
			"icons/deploy.svg",
		),
	})
}
