// Code generated by Kubegraph; DO NOT EDIT.

package v1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	batchV1 "k8s.io/api/batch/v1"
)

// JobObject alias for batchV1.Job
type JobObject = batchV1.Job

// JobAdapterObjectType reflected type of *batchV1.Job
var JobAdapterObjectType = reflect.TypeOf((*batchV1.Job)(nil))

// GetJobAdapter retrieves *JobAdapter from the registry
func GetJobAdapter() (*JobAdapter, error) {
	adapter, err := registry.GetAdapter[*batchV1.Job]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*JobAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// JobAdapter implements an adapter for batchV1.Job
type JobAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *batchV1.Job
func (this *JobAdapter) CastObject(obj registry.RuntimeObject) (*batchV1.Job, error) {
	casted, ok := obj.(*batchV1.Job)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *batchV1.Job
// nodes stored on a graph
func (this *JobAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*batchV1.Job, error) {
	objects, err := statefulGraph.GetObjects(JobAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*batchV1.Job, len(objects))
	for key, object := range objects {
		casted, ok := object.(*batchV1.Job)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *batchV1.Job
func (this *JobAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(JobAdapterObjectType, name)
}

func (this *JobAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/job.svg")
}

// init registers JobAdapter
func init() {
	registry.MustRegister(&JobAdapter{
		registry.NewAdapter(
			JobAdapterObjectType,
			"icons/job.svg",
		),
	})
}
