// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package pod

import (
	"github.com/wwmoraes/kubegraph/internal/adapter"
	"reflect"
)

// Injectors from wire.go:

func Register(resourceType reflect.Type, iconPath string) error {
	resourceData := adapter.NewResourceData(resourceType, iconPath)
	adapterResourceTransformer := New(resourceData)
	error2 := adapter.Register(adapterResourceTransformer)
	return error2
}
