// Code generated by Kubegraph; DO NOT EDIT.

package v1beta1

import (
	"fmt"
	"reflect"

	"github.com/wwmoraes/kubegraph/internal/registry"
	policyV1beta1 "k8s.io/api/policy/v1beta1"
)

// PodSecurityPolicyObject alias for policyV1beta1.PodSecurityPolicy
type PodSecurityPolicyObject = policyV1beta1.PodSecurityPolicy

// PodSecurityPolicyAdapterObjectType reflected type of *policyV1beta1.PodSecurityPolicy
var PodSecurityPolicyAdapterObjectType = reflect.TypeOf((*policyV1beta1.PodSecurityPolicy)(nil))

// GetPodSecurityPolicyAdapter retrieves *PodSecurityPolicyAdapter from the registry
func GetPodSecurityPolicyAdapter() (*PodSecurityPolicyAdapter, error) {
	adapter, err := registry.GetAdapter[*policyV1beta1.PodSecurityPolicy]()
	if err != nil {
		return nil, err
	}
	casted, ok := adapter.(*PodSecurityPolicyAdapter)
	if !ok {
		return nil, fmt.Errorf("unable get adapter: %w", registry.ErrIncompatibleType)
	}
	return casted, nil
}

// PodSecurityPolicyAdapter implements an adapter for policyV1beta1.PodSecurityPolicy
type PodSecurityPolicyAdapter struct {
	registry.Adapter
}

// CastObject casts a runtime.Object to *policyV1beta1.PodSecurityPolicy
func (this *PodSecurityPolicyAdapter) CastObject(obj registry.RuntimeObject) (*policyV1beta1.PodSecurityPolicy, error) {
	casted, ok := obj.(*policyV1beta1.PodSecurityPolicy)
	if !ok {
		return casted, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
	}

	return casted, nil
}

// GetGraphObjects returns a map of all *policyV1beta1.PodSecurityPolicy
// nodes stored on a graph
func (this *PodSecurityPolicyAdapter) GetGraphObjects(statefulGraph registry.StatefulGraph) (map[string]*policyV1beta1.PodSecurityPolicy, error) {
	objects, err := statefulGraph.GetObjects(PodSecurityPolicyAdapterObjectType)
	if err != nil {
		return nil, err
	}

	castedObjects := make(map[string]*policyV1beta1.PodSecurityPolicy, len(objects))
	for key, object := range objects {
		casted, ok := object.(*policyV1beta1.PodSecurityPolicy)
		if !ok {
			return nil, fmt.Errorf("unable convert object: %w", registry.ErrIncompatibleType)
		}
		castedObjects[key] = casted
	}
	return castedObjects, nil
}

// GetGraphNode returns the node value representing a *policyV1beta1.PodSecurityPolicy
func (this *PodSecurityPolicyAdapter) GetGraphNode(statefulGraph registry.StatefulGraph, name string) (registry.Node, error) {
	return statefulGraph.GetNode(PodSecurityPolicyAdapterObjectType, name)
}

func (this *PodSecurityPolicyAdapter) AddStyledNode(graph registry.StatefulGraph, obj registry.RuntimeObject) (registry.Node, error) {
	resource, err := this.CastObject(obj)
	if err != nil {
		return nil, err
	}

	name := fmt.Sprintf("%s.%s~%s", resource.APIVersion, resource.Kind, resource.Name)
	return graph.AddStyledNode(this.GetType(), obj, name, resource.Name, "icons/psp.svg")
}

// init registers PodSecurityPolicyAdapter
func init() {
	registry.MustRegister(&PodSecurityPolicyAdapter{
		registry.NewAdapter(
			PodSecurityPolicyAdapterObjectType,
			"icons/psp.svg",
		),
	})
}
