@startuml
autoactivate on

!include components-v1.iuml

Main o-->> Icons : import
Main o-->> Kubegraph : import
Kubegraph o-->> Registry : import
Kubegraph o-->> Adapters : import
Adapters o-->> Registry : import

Adapters -> Adapters : init
Adapters -> Adapters : New
return adapter
Adapters -> Registry : MustRegister
Registry -> Registry : once.Do/get
return registry
Registry -> Adapters : set registry
return
Registry -> Registry : append adapter
return
return
return

title Kubegraph CLI init v1

@enduml
